apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auction
  template:
    metadata:
      labels:
        app: auction
    spec:
      containers:
      - name: auction
        image: piyush1048/auction:0.0.1.RELEASE
      
        

---

apiVersion: v1
kind: Service
metadata:
  name: auction-service
spec:
  selector:
    name: auction
  ports:
    - name: http
      port: 8002
      targetPort: 3002
  type: LoadBalancer
