apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: piyush1048/frontend:0.0.1.RELEASE
      
        

---

apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    name: customer
  ports:
    - name: http
      port: 8001
      targetPort: 3001
  type: LoadBalancer
