apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: piyush1048/frontend:0.0.1.RELEASE
      
        

---

apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    name: product
  ports:
    - name: http
      port: 8005
      targetPort: 3000
  type: LoadBalancer
